service: api-serverless

app: analyze-images-app
org: jardelgoncalves1996

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: "Allow"
      Action:
        - translate:TranslateText
      Resource: "*"


functions:
  analyze-image:
    handler: handler.main
    events:
      - http:
          path:  analyze
          method: get
          cors: true